baseURL = "https://modprox.org/"
languageCode = "en-us"
title = "modprox docs"
theme = "kraiklyn"

pygmentsCodeFences = true
pygmentsStyle = "monokailight"



[params]
sidebarColor = "gray"
customCss = ["css/custom.css"]

[[menu.shortcuts]]
name = "modprox source on github"
url = "https://github.com/modprox"
weight = 10

[[menu.shortcuts]]
name = "indeed engineering blog"
url = "https://engineering.indeedblog.com/blog/"
weight = 20
